LMS/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

urlpatterns = [
    path('', include('library.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

library/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'library'

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),

    # sign up url
    path('register/', views.register, name='register'),

    path('member_list', views.member_list, name='member_list'),
    path('member/create/', views.member_new, name='member_new'),
    path('member/<int:pk>/edit/', views.member_edit, name='member_edit'),
    path('member/<int:pk>/delete/', views.member_delete, name='member_delete'),

    # path('librarian_list', views.librarian_list, name='librarian_list'),
    # path('librarian/<int:pk>/edit/', views.librarian_edit, name='librarian_edit'),
    # path('librarian/<int:pk>/delete/', views.librarian_delete, name='librarian_delete'),

    path('book_list', views.book_list, name='book_list'),
    path('book/create/', views.book_new, name='book_new'),
    path('book/<int:pk>/edit/', views.book_edit, name='book_edit'),
    path('book/<int:pk>/delete/', views.book_delete, name='book_delete'),

    path('genre_list', views.genre_list, name='genre_list'),
    path('genre/create/', views.genre_new, name='genre_new'),
    path('genre/<int:pk>/edit/', views.genre_edit, name='genre_edit'),
    path('genre/<int:pk>/delete/', views.genre_delete, name='genre_delete'),

    path('author_list', views.author_list, name='author_list'),
    path('author/create/', views.author_new, name='author_new'),
    path('author/<int:pk>/edit/', views.author_edit, name='author_edit'),
    path('author/<int:pk>/delete/', views.author_delete, name='author_delete'),

    path('borrow_list', views.borrow_list, name='borrow_list'),
    path('borrow/create/', views.borrow_new, name='borrow_new'),
    path('borrow/<int:pk>/edit/', views.borrow_edit, name='borrow_edit'),
    path('borrow/<int:pk>/delete/', views.borrow_delete, name='borrow_delete'),

    path('pdf/', views.borrow_summary_pdf, name='borrow_summary_pdf'),
    path('pdf/', views.email_borrow_summary_pdf, name='email_borrow_summary_pdf'),
]

library/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class SignUpForm(UserCreationForm):
    CHOICES = (
        ('Member', 'Member'),
        ('Librarian', 'Librarian'),
    )
    user_type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'mobile_num', 'password1', 'password2', 'user_type')

    def save(self):
        user = super().save(commit=False)
        if self.user_type == 'Member':
            user = super().save(commit=False)
            user.is_staff = False
            user.save()
            Member.objects.create(user=user)
        else:
            user = super().save(commit=False)
            user.is_staff = True
            user.is_superuser = True
            user.save()
            Librarian.objects.create(user=user)
        return user


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ('first_name', 'last_name', 'email', 'mobile_num',
                  'work_phone', 'street_address', 'city', 'state', 'zip', 'interests',)


class MemberCreationForm(UserCreationForm):
    interests = forms.CharField(required=False, label='',
                                widget=forms.Textarea(attrs={'placeholder': 'Additional Information'}))

    class Meta(UserCreationForm):
        model = Member
        fields = ('first_name', 'last_name', 'email', 'mobile_num', 'work_phone', 'street_address', 'city', 'state',
                  'zip', 'interests',)

    def __init__(self, *args, **kwargs):
        super(MemberCreationForm, self).__init__(*args, **kwargs)
        self.fields.pop('password1')
        self.fields.pop('password2')

    def save(self, commit=True, uname="unknown", pword="unknown"):
        self.cleaned_data['password1'] = pword
        member = super(MemberCreationForm, self).save(commit=False)
        member.username = uname
        member.first_name = self.cleaned_data['first_name']
        member.last_name = self.cleaned_data['last_name']

        if commit:
            member.save()
        return member


class LibrarianCreationForm(UserCreationForm):
    work_phone = forms.CharField(required=False, label='',
                                 widget=forms.Textarea(attrs={'placeholder': 'Additional Information'}))

    class Meta(UserCreationForm):
        model = Librarian
        fields = ('first_name', 'last_name', 'email', 'mobile_num', 'work_phone', 'street_address', 'city', 'state',
                  'zip',)

    def __init__(self, *args, **kwargs):
        super(LibrarianCreationForm, self).__init__(*args, **kwargs)
        self.fields.pop('password1')
        self.fields.pop('password2')

    def save(self, commit=True, uname="unknown", pword="unknown"):
        self.cleaned_data['password1'] = pword
        librarian = super(LibrarianCreationForm, self).save(commit=False)
        librarian.username = uname
        librarian.is_staff = True
        librarian.first_name = self.cleaned_data['first_name']
        librarian.last_name = self.cleaned_data['last_name']

        if commit:
            librarian.save()
        return librarian


class BorrowForm(forms.ModelForm):
    class Meta:
        model = Borrow
        fields = ('member', 'book_name', 'author_name', 'genre_name', 'issue_date', 'return_date',)


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'isbn', 'author_name', 'genre_name', 'available_copies',)


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ('name', 'description',)


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        # fields = ('first_name', 'last_name', 'date_of_birth', 'died', 'description',)
        fields = ('name', 'description',)

library/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.core.mail import EmailMultiAlternatives, EmailMessage
from django.template.loader import get_template
from library.forms import *
from library.models import *


def home(request):
    return render(request, 'library/home.html', {'library': home})


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("/home")
    else:
        form = RegisterForm()

    return render(request, "registration/signup.html", {"form": form})


# def register(request):
#     if request.method == "POST":
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=password)
#             login(request, user)
#             return redirect("/home")
#     else:
#         form = SignUpForm()
#
#     return render(request, "registration/signup.html", {"form": form})


def signup_member(request):
    if request.method == 'POST':
        u = request.POST.get('first_name', '').lower() + "." + request.POST.get('last_name', '').lower()
        e = request.POST.get('email')
        p = User.objects.make_random_password(length=8)
        form = MemberCreationForm(request.POST)

        if form.is_valid():
            form.save(uname=u, pword=p)
            form.save_m2m()
            sendEmail_signup(e, p, u)
            return render(request, 'registration/signup_email.html')

        else:
            return render(request, 'registration/signup.html', {'form': form})
    else:
        form = MemberCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


# method for sending email after member registration
def sendEmail_signup(email, pwd, username):
    subject = "Welcome to Library Management System"
    content = {'pwd': pwd, 'uname': username, 'lms_site_name': 'Library Management System'}
    from_email = settings.EMAIL_HOST_USER
    to_email = email
    with open("library/templates/registration/email_review_signup.txt") as f:
        signup_message = f.read()
    message = EmailMultiAlternatives(subject=subject, body=signup_message, from_email=from_email,
                                     to=[to_email], )
    html_template = get_template("registration/signup_email_body.html").render(context=content)
    message.attach_alternative(html_template, "text/html")
    message.send()


@login_required
def member_list(request):
    member = Member.objects.all()
    return render(request, 'library/member_list.html', {'members': member})


@login_required
def member_edit(request, pk):
    member = get_object_or_404(Member, pk=pk)
    if request.method == "POST":
        # update
        form = MemberForm(request.POST, instance=member)
        if form.is_valid():
            member = form.save(commit=False)
            member.created_date = timezone.now()
            member.save()
            member = Member.objects.all()
            return render(request, 'library/member_list.html', {'members': member})
    else:
        # edit
        form = MemberForm(instance=member)
    return render(request, 'library/member_edit.html', {'form': form})


@login_required
def member_delete(request, pk):
    member = get_object_or_404(Member, pk=pk)
    member.delete()
    return redirect('library:member_list')


@login_required
def member_new(request):
    if request.method == "POST":
        form = MemberForm(request.POST)
        if form.is_valid():
            member = form.save(commit=False)
            member.save()
            members = Member.objects.all()
            return render(request, 'library/member_list.html', {'members': members})
    else:
        form = MemberForm()
    return render(request, 'library/member_new.html', {'form': form})


@login_required
def borrow_list(request):
    borrows = Borrow.objects.all()
    return render(request, 'library/borrow_list.html', {'borrows': borrows})


@login_required
def borrow_new(request):
    if request.method == "POST":
        form = BorrowForm(request.POST)
        if form.is_valid():
            borrow = form.save(commit=False)
            borrow.save()
            borrows = Borrow.objects.all()
            return render(request, 'library/borrow_list.html', {'borrows': borrows})
    else:
        form = BorrowForm()
    return render(request, 'library/borrow_new.html', {'form': form})


@login_required
def borrow_edit(request, pk):
    borrow = get_object_or_404(Borrow, pk=pk)
    if request.method == "POST":
        form = BorrowForm(request.POST, instance=borrow)
        if form.is_valid():
            borrow = form.save()
            borrow.updated_date = timezone.now()
            borrow.save()
            borrows = Borrow.objects.all()
            return render(request, 'library/borrow_list.html', {'borrows': borrows})
    else:
        form = BorrowForm(instance=borrow)
    return render(request, 'library/borrow_edit.html', {'form': form})


@login_required
def borrow_delete(request, pk):
    borrow = get_object_or_404(Borrow, pk=pk)
    borrow.delete()
    return redirect('library:borrow_list')


@login_required
def book_list(request):
    books = Book.objects.all()
    return render(request, 'library/book_list.html', {'books': books})


@login_required
def book_new(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            # book.created_date = timezone.now()
            book.save()
            books = Book.objects.all()
            return render(request, 'library/book_list.html', {'books': books})
    else:
        form = BookForm()
    return render(request, 'library/book_new.html', {'form': form})


@login_required
def book_edit(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            book = form.save()
            book.updated_date = timezone.now()
            book.save()
            books = Book.objects.all()
            return render(request, 'library/book_list.html', {'books': books})
    else:
        form = BookForm(instance=book)
    return render(request, 'library/book_edit.html', {'form': form})


@login_required
def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    book.delete()
    return redirect('library:book_list')


@login_required
def author_list(request):
    authors = Author.objects.all()
    return render(request, 'library/author_list.html', {'authors': authors})


@login_required
def author_new(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.save()
            authors = Author.objects.all()
            return render(request, 'library/author_list.html', {'authors': authors})
    else:
        form = AuthorForm()
    return render(request, 'library/author_new.html', {'form': form})


@login_required
def author_edit(request, pk):
    author = get_object_or_404(Author, pk=pk)
    if request.method == "POST":
        form = AuthorForm(request.POST, instance=author)
        if form.is_valid():
            author = form.save()
            author.save()
            authors = Author.objects.all()
            return render(request, 'library/author_list.html', {'authors': authors})
    else:
        form = AuthorForm(instance=author)
    return render(request, 'library/author_edit.html', {'form': form})


@login_required
def author_delete(request, pk):
    author = get_object_or_404(Author, pk=pk)
    author.delete()
    return redirect('library:author_list')


@login_required
def genre_list(request):
    genres = Genre.objects.all()
    return render(request, 'library/genre_list.html', {'genres': genres})


@login_required
def genre_new(request):
    if request.method == "POST":
        form = GenreForm(request.POST)
        if form.is_valid():
            genre = form.save(commit=False)
            genre.save()
            genres = Genre.objects.all()
            return render(request, 'library/genre_list.html', {'genres': genres})
    else:
        form = GenreForm()
    return render(request, 'library/genre_new.html', {'form': form})


@login_required
def genre_edit(request, pk):
    genre = get_object_or_404(Genre, pk=pk)
    if request.method == "POST":
        form = GenreForm(request.POST, instance=genre)
        if form.is_valid():
            genre = form.save()
            genre.save()
            genres = Genre.objects.all()
            return render(request, 'library/genre_list.html', {'genres': genres})
    else:
        form = GenreForm(instance=genre)
    return render(request, 'library/genre_edit.html', {'form': form})


@login_required
def genre_delete(request, pk):
    genre = get_object_or_404(Genre, pk=pk)
    genre.delete()
    return redirect('library:genre_list')


from django.http import HttpResponse
from django.views.generic import View
from library.utils import render_to_pdf
from django.template.loader import get_template


def borrow_summary_pdf(request):
    borrows = Borrow.objects.all()
    context = {'borrows': borrows, }
    template = get_template('library/borrow_summary_pdf.html')
    html = template.render(context)

library/templates/library/author_edit.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <html lang="en">
    <body>
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-heading">
                    <div class="panel-heading">Edit Author</div>
                </div>
            </div>
        </div>
        <form action="" method="post" class="custom-form col-md-6">{% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="save btn btn-primary">Update</button>
        </form>
    </div>
    </body>
    </html>
{% endblock %}

library/templates/library/author_new.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-heading">
                    <div class="panel-heading">Add New Author</div>
                </div>
            </div>
        </div>
        <form method="POST" class="custom-form col-md-6">{% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="save btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

library/templates/library/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Library Management System</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static "images/library.ico" %}" type="image/ico" sizes="16x16">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        header {
            background-image: url('{% static "images/bg_image_1.jpg" %}');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;"
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }

        body {
            background-image: url("{% static "images/library-bg.jpg" %}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }

        .custom-form {
            max-width: 100%;
            display: block;
            padding: 20px;
            border: 2px solid antiquewhite;
            background-color: white;
        }
    </style>
</head>
<body id="app-layout">

<nav class="navbar navbar-inverse" style="background: midnightblue">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a style="color: white" class="navbar-brand" href="/">
                Library Management System
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a style="color: white" href="{% url 'library:home' %}">Home</a></li>
                <li><a style="color: white" href="{% url 'library:book_list' %}">Books</a></li>
                <li><a style="color: white" href="{% url 'library:author_list' %}">Authors</a></li>
                <li><a style="color: white" href="{% url 'library:member_list' %}">Members</a></li>
                <li><a style="color: white" href="{% url 'library:borrow_list' %}">Borrow Books</a></li>
                <li><a style="color: white" href="{% url 'library:genre_list' %}">Genres</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" style="color: white" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            Hi, {{ user.username }}!
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a style="color: darkslateblue"  href="{% url 'password_change' %}">Change password</a></li>
                            <li><a style="color: darkslateblue"  href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a style="color: white" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <li><a style="color: white" href="{% url 'library:register' %}"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

library/templates/library/book_delete.html
{% extends 'library/base.html' %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ book.title }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

library/templates/library/book_edit.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-heading">
                    <div class="panel-heading">Edit Book</div>
                </div>
            </div>
        </div>
        <form action="" method="post" class="custom-form col-md-6">{% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="save btn btn-primary">Update</button>
        </form>
    </div>
    </body>
    </html>
{% endblock %}

library/templates/library/book_new.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-heading">
                    <div class="panel-heading">Add New Book</div>
                </div>
            </div>
        </div>
        <form method="POST" class="custom-form col-md-6">{% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="save btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

library/templates/library/borrow_list.html
{% extends 'library/base.html' %}
{% block content %}
    <html lang="en">
    <body>
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-heading">
                    <div class="panel-heading">Borrowed Books Information!</div>
                </div>
            </div>
        </div>
        <div>
            <table class="table table-hover table-responsive-lg">
                <thead>
                <tr class="bg-info">
                    <th>Member</th>
                    <th>Book Name</th>
                    <th>Author Name</th>
                    <th>Genre Name</th>
                    <th>Issue Date</th>
                    <th>Return Date</th>
                    <th colspan="3">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for borrow in borrows %}
                    <tr bgcolor="white">
                        <td>{{ borrow.member }}</td>
                        <td>{{ borrow.book_name }}</td>
                        <td>{{ borrow.author_name }}</td>
                        <td>{{ borrow.genre_name }}</td>
                        <td>{{ borrow.issue_date }}</td>
                        <td>{{ borrow.return_date }}</td>
                        <td><a href="{% url 'library:borrow_edit' pk=borrow.pk %}"
                               class="btn btn-warning">Edit</a></td>
                        <td><a href="{% url 'library:borrow_delete' pk=borrow.pk %}"
                               onclick="return confirm('Are you sure you want to delete?')"
                               class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div class="row">
                <a href="{% url 'library:borrow_new' %}" class="row"><span
                        class="btn btn-primary">Borrow Book</span></a>
                <a href="{% url 'library:borrow_summary_pdf' %}" class="row"><span
                        class="btn btn-primary">Download Borrow Summary Pdf</span></a>
                <a href="{% url 'library:email_borrow_summary_pdf' %}" class="row"><span
                        class="btn btn-primary">Email Borrow Summary Pdf</span></a>
            </div>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

library/templates/library/borrow_new.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-heading">
                    <div class="panel-heading">Borrow Book</div>
                </div>
            </div>
        </div>
        <form method="POST" class="custom-form col-md-6">{% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="save btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

library/templates/library/genre_list.html
{% extends 'library/base.html' %}
{% block content %}
    <html lang="en">
    <body>
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-heading">
                    <div class="panel-heading">Genre Information!</div>
                </div>
            </div>
        </div>
        <div>
            <table class="table table-hover table-responsive-lg text-center">
                <thead>
                <tr class="bg-info">
                    <th>Genre Name</th>
                    <th colspan="3">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for genre in genres %}
                    <tr bgcolor="white">
                        <td>{{ genre.name }}</td>
                        <td><a href="{% url 'library:genre_edit' pk=genre.pk %}"
                               class="btn btn-warning">Edit</a></td>
                        <td><a href="{% url 'library:genre_delete' pk=genre.pk %}"
                               onclick="return confirm('Are you sure you want to delete?')"
                               class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div class="row">
                <a href="{% url 'library:genre_new' %}" class="row"><span
                        class="btn btn-primary">Add Genre</span></a>
            </div>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

library/templates/library/genre_new.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-heading">
                    <div class="panel-heading">Add New Genre</div>
                </div>
            </div>
        </div>
        <form method="POST" class="custom-form col-md-6">{% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="save btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

library/templates/library/member_delete.html
{% extends 'library/base.html' %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ member.get_full_name }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

library/templates/library/member_edit.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-heading">
                    <div class="panel-heading">Edit Member Info</div>
                </div>
            </div>
        </div>
        <form action="" method="post" class="custom-form col-md-6">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="save btn btn-primary">Update</button>
        </form>
    </div>
    </body>
    </html>
{% endblock %}

library/templates/library/member_new.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-heading">
                    <div class="panel-heading">Add New Member</div>
                </div>
            </div>
        </div>
        <form method="POST" class="custom-form col-md-6">{% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="save btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}